# Generated by Django 3.2.3 on 2022-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailleur',
            name='type_user',
            field=models.CharField(choices=[('pmr', 'locataire'), ('bailleur', 'loueur')], default='bailleur', max_length=100),
        ),
        migrations.AlterField(
            model_name='pmr',
            name='type_user',
            field=models.CharField(choices=[('pmr', 'locataire'), ('bailleur', 'loueur')], default='pmr', max_length=100),
        ),
    ]
